### ISSUE TITLE
Ver cajas mensuales disponibles

### ISSUE THREAD

**Issue by seblaz** [ConstanzaFrutos/micava#11]
Como amante del vino deseo ver las cajas mensuales disponibles para tomar una decisión de compra.

Cada opción de caja debe incluir:
- Una descripción
- Precio del mercado
- Precio en promoción por comprar la caja

Ejemplo: https://autogestion.bonvivir.com/selection

**Comment by seblaz** [comment]
Related: #20

**Comment by seblaz** [comment]
Pendiente:
- No mostrar vinos de marcas específicas
- Mostrar precio del mercado comparado con el de la caja

**Comment by IgVelasco** [comment]
Esta la podemos cerrar o que te gustaria agregarle? @seblaz

**Comment by seblaz** [comment]
@IgVelasco lo que puse en el comentario de arriba

**Comment by IgVelasco** [comment]
Solamente los comments esos nada relacionado al carrito? eso lo solucionabamos con compra directa no?

**Comment by seblaz** [comment]
Creo que lo de la compra lo podemos tratar en la historia #12 . En mi opinión no hace falta un carrito, pero mejor charlémoslo en grupo eso. Igualmente creo que a esta historia no le afecta esa definición, a lo mejor dependiendo de lo que decidamos habrá que cambiar un poco el botón de comprar nomás.

**Comment by jomedina96** [comment]
![Screenshot from 2021-08-08 00-20-25](https://user-images.githubusercontent.com/17090039/128619645-4075dba9-3bfc-4291-ad88-0769e8a16069.png)

**Comment by jomedina96** [comment]
https://github.com/ConstanzaFrutos/micava/pull/53
